modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/Cryptic-Mushroom/The-Midnight/issues"
license = "Custom License, see GitHub"

[[mods]]
modId = "midnight"
version = "${file.jarVersion}"
displayName = "The Midnight"
updateJSONURL = "https://raw.githubusercontent.com/Cryptic-Mushroom/The-Midnight/rewrite/versioninfo/update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/the-midnight"
logoFile = "logo.png" # TODO: WE NEED A NEW LOGO!!!
credits = "Cipher Zero X, Shadew, Jonathing, Lachney, 123wdog, bagu_chan"
authors = "Cryptic Mushroom"
description = '''The Midnight has been rewritten from the ground up and is currently in an unstable alpha. Expect more content soon!

This mod is a huge collaborative effort with tons of different ideas, coding, and textures pitched in by varying individuals who came together to build something great. We wouldn't be where we are today without the help of those here today and those who worked on this mod in the past.

The Midnight Team Active Developers
Cipher Zero X - Project Lead, Lead Designer, Modeler
Shadew - Lead Programmer, Designer
Jonathing - Project Lead, Community Manager, Lead QA, Programmer, Musician
Lachney - Lead Sound Designer, Lead Musician
123wdog - Lead Modeler

Active Collaborators
bagu_chan - Programmer, Texturer

Former and Inactive Developers
gegy1000 - Programmer
Martacus - Programmer
arthurbambous - Programmer
Corail31 - Programmer
Endergized - Texturer
Five (Paradiscal) - Texturer
MCVinnyq - Texturer, Modeler

The Midnight is still in active development and we'd love to hear your feedback! Click the link near the top of this page to view information on our Discord server, active developers, and plans for the future of this mod.'''

[[dependencies.midnight]]
modId = "forge"
mandatory = true
versionRange = "[36.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.midnight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5]"
ordering = "NONE"
side = "BOTH"
