# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: The Midnight (1.15.2 Experimental)

on:
  push:
    branches:
      - experiment/1.15.2-*
      - feature/1.15.2-*
    paths-ignore:
      - '.github/**'
      - 'curseforge/**'
      - 'README.md'
      - 'LICENSE'
      - 'changelog.json'
      - '.gitignore'
      - '.gitattributes'
    tags-ignore:
      - '*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update CI Workspace
      uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk
        architecture: x64

    - name: Build The Midnight for Minecraft 1.15.2
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 4.10.3
        arguments: build

    - name: Upload the Build Output to GitHub
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: build-output-${{ github.sha }}
        # A file, directory or wildcard pattern that describes what to upload
        path: build/libs/*.jar
